import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Copyright } from "lucide-react";
import Curtain from "./components/Curtain";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='relative bg-cream min-h-screen font-serif isolate z-10'>
				<header className='header p-4 flex justify-between z-1'>
					<div className='logo font-serif text-xl md:text-2xl'>
						Vihari Cherukumalli
					</div>
					<div className='right flex justify-between align-center gap-4 text-base md:text-xl'>
						<div className='about'>
							<Link href='/about'>About</Link>
						</div>
						<div className='blog'>
							<Link href='/blog'>blog</Link>
						</div>
					</div>
				</header>
				<section className='landing  flex my-48 md:my-96 align-center flex-col z-1'>
					<div className='name text-center text-5xl relative md:text-9xl 2xl:text-[148px] flex flex-col !leading-[0.9] items-center'>
						<div className='name1 flex'>
							<div className='image  w-[12vw]  items-center  bottom-0 relative mr-3'>
								<Image src={"/reelCamera.svg"} alt='' fill />
							</div>
							Vihari
							<div className='image  w-[15vw] md:w-[8vw] items-center bottom-0 relative object-cover'>
								<Image src={"/tripod.svg"} alt='' fill />
							</div>
						</div>
						<div className='name2 flex gap-[-4px]'>
							<div className='image  w-[9vw]  items-center  bottom-0 relative'>
								<Image src={"/reel.svg"} alt='' fill />
							</div>
							Cherukumalli{" "}
							<div className='image  w-[9vw] md:w-[7vw]  items-center  bottom-0 relative'>
								<Image src={"/camera.svg"} alt='' fill />
							</div>
						</div>
					</div>
					<div className='professions  text-center flex gap-5 justify-center text-sm md:text-2xl mt-4'>
						<div>Photographer</div>
						<div>Cinematographer</div>
						<div>Director</div>
						<div>Film Editor</div>
					</div>
					<div className='buttons flex gap-8 justify-center mt-12 md:mt-24'>
						<button className='outline outline-1 px-2 py-1 md:px-4 md:py-2 flex justify-center items-center text-base md:text-xl'>
							Get in touch
						</button>
						<button className='outline outline-1 px-2 py-1 md:px-4 md:py-2 flex justify-center items-center text-base md:text-xl '>
							See my work
						</button>
					</div>
				</section>
				<section className='min-h-screen max-w-[1600px] object-contain w-full mx-auto flex flex-col px-4 md:px-12 z-1'>
					<div className='mb-24'>
						<div className='text-center text-3xl md:text-6xl w-[300px] md:w-[600px] mx-auto mb-12 md:mb-24'>
							A camera is the world’s greatest orator.
						</div>
						<div className='image flex w-full aspect-video object-contain relative'>
							<Image
								src={"/images/portfolio_main.jpg"}
								alt='A photo of me (Vihari) looking a wall of photos'
								fill
							/>
						</div>
					</div>
					<div className='mb-24'>
						<div className='text-center text-3xl md:text-6xl w-[300px] md:w-[600px] mx-auto mb-12 md:mb-24 z-1'>
							With images that tell a tale
						</div>
						<div className='image flex w-full aspect-video object-contain relative'>
							<Image
								src={"/images/church.jpg"}
								alt='A photo of the inside of a church.'
								fill
							/>
						</div>
					</div>
					<div className='mb-24'>
						<div className='text-center text-3xl md:text-6xl w-[300px] md:w-[600px] mx-auto mb-12 md:mb-24'>
							That keep you wanting for more.
						</div>
						<div className='columns-1 md:columns-2 gap-8'>
							<div className='image flex w-full aspect-video object-contain relative mb-6'>
								<Image
									src={"/images/image3.jpg"}
									alt='A photo of the inside of a church.'
									fill
								/>
							</div>
							<div className='image flex w-full aspect-video object-contain relative mb-6'>
								<Image
									src={"/images/image6.jpg"}
									alt='A photo of the inside of a church.'
									fill
								/>
							</div>
							<div className='image flex w-full aspect-video object-contain relative mb-6'>
								<Image
									src={"/images/image5.jpg"}
									alt='A photo of the inside of a church.'
									fill
								/>
							</div>
							<div className='image flex w-full aspect-square object-contain relative  mb-6'>
								<Image
									src={"/images/image4.jpg"}
									alt='A photo of the inside of a church.'
									fill
								/>
							</div>

							<div className='image flex w-full aspect-video object-contain relative mb-6'>
								<Image
									src={"/images/image7.jpg"}
									alt='A photo of the inside of a church.'
									fill
								/>
							</div>
						</div>
						<button className='outline outline-1 px-2 py-1 md:px-4 md:py-2 flex justify-center items-center text-base md:text-xl mt-10 mx-auto gap-4'>
							View more <ArrowRight strokeWidth={1} />
						</button>
					</div>
				</section>
				<footer className='mt-10 border border-t-1  border-black flex justify-center items-center flex-col py-4'>
					<div className='logo text-3xl'>Vihari Cherukumalli</div>
					<div className='flex justify-center items-center'>
						<Copyright strokeWidth={1} />
						{new Date().getFullYear()}
					</div>
				</footer>
				<Curtain className='z-100' />
			</main>
		</>
	);
}
